# theme: jekyll-theme-cayman
# Site settings
title: Abdelrahman Shaker
email: abdelrahman.m.shaker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amshaker.github.io" # the base hostname & protocol for your site
github_username:  amshaker

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "PhD student"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "https://scholar.google.com/citations?hl=en&user=eEz4Wu4AAAAJ"
# google_site_verification: ""
# bing_webmastertools_id: ""
